import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const output = `// Generated by scripts/generate-types.mjs.
// napi-rs native declarations are generated in native.d.ts during npm run build.

export interface LaunchOptions {
  headless?: boolean;
  executablePath?: string;
  channel?: string;
  args?: string[];
  ignoreAllDefaultArgs?: boolean;
  ignoreDefaultArgs?: string[];
  timeout?: number;
  userDataDir?: string;
  env?: Record<string, string | number | boolean>;
  chromiumSandbox?: boolean;
  proxy?: {
    server: string;
    bypass?: string;
    username?: string;
    password?: string;
  };
}

export interface GotoOptions {
  waitUntil?: 'load' | 'domcontentloaded' | 'networkidle' | 'commit';
  timeout?: number;
  referer?: string;
}

export interface ActionOptions {
  timeout?: number;
}

export interface ScreenshotOptions {
  path?: string;
  fullPage?: boolean;
  clip?: { x: number; y: number; width: number; height: number; scale?: number };
  timeout?: number;
  type?: 'png' | 'jpeg' | 'webp';
  quality?: number;
  omitBackground?: boolean;
}

export class Browser {
  newPage(): Promise<Page>;
  close(): Promise<void>;
  wsEndpoint(): string;
}

export class Page {
  goto(url: string, options?: GotoOptions): Promise<unknown | null>;
  click(selector: string, options?: ActionOptions): Promise<void>;
  fill(selector: string, value: string, options?: ActionOptions): Promise<void>;
  title(options?: ActionOptions): Promise<string>;
  textContent(selector: string, options?: ActionOptions): Promise<string | null>;
  evaluate<T = unknown>(expression: string | ((arg?: unknown) => T | Promise<T>), arg?: unknown, options?: ActionOptions): Promise<T>;
  screenshot(options?: ScreenshotOptions): Promise<Buffer>;
  close(options?: { timeout?: number; runBeforeUnload?: boolean }): Promise<void>;
}

export const chromium: {
  launch(options?: LaunchOptions): Promise<Browser>;
  executablePath(): Promise<string>;
};

declare const rustwright: {
  chromium: typeof chromium;
  Browser: typeof Browser;
  Page: typeof Page;
};

export default rustwright;
`;

writeFileSync(resolve('index.d.ts'), output);
