"""Rust-backed browser automation with a Playwright-shaped Python API."""

from ._compat import disable_playwright_compat, enable_playwright_compat
from .sync_api import (
    Browser,
    BrowserContext,
    BrowserType,
    BackendMarker,
    ConsoleMessage,
    ElementHandle,
    Error,
    Download,
    FileChooser,
    Frame,
    FrameLocator,
    JSHandle,
    Locator,
    Page,
    Playwright,
    Response,
    TargetClosedError,
    TimeoutError,
    Video,
    backend_marker,
    expect,
    sync_playwright,
)
from .async_api import async_playwright

__all__ = [
    "Browser",
    "BrowserContext",
    "BrowserType",
    "BackendMarker",
    "ConsoleMessage",
    "Download",
    "ElementHandle",
    "Error",
    "FileChooser",
    "Frame",
    "FrameLocator",
    "JSHandle",
    "Locator",
    "Page",
    "Playwright",
    "Response",
    "TargetClosedError",
    "TimeoutError",
    "Video",
    "backend_marker",
    "disable_playwright_compat",
    "enable_playwright_compat",
    "expect",
    "async_playwright",
    "sync_playwright",
]
